//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azuki.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azuki.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-loading Modules for startup....
        /// </summary>
        internal static string AutoLoadingModules {
            get {
                return ResourceManager.GetString("AutoLoadingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - Command not found. ({0})..
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to voice channel (0) in {1}..
        /// </summary>
        internal static string ConnectedToVoiceChannel {
            get {
                return ResourceManager.GetString("ConnectedToVoiceChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created CoreHandler for shard {0}, Current count: {1}..
        /// </summary>
        internal static string CreatedHandler {
            get {
                return ResourceManager.GetString("CreatedHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered guild ({0})..
        /// </summary>
        internal static string DiscoveredGuild {
            get {
                return ResourceManager.GetString("DiscoveredGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command: {0}({1})..
        /// </summary>
        internal static string ExecutingCommand {
            get {
                return ResourceManager.GetString("ExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Command {0}..
        /// </summary>
        internal static string FoundCommand {
            get {
                return ResourceManager.GetString("FoundCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Command {0}, it was rejected..
        /// </summary>
        internal static string FoundCommandRejected {
            get {
                return ResourceManager.GetString("FoundCommandRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Reason: Wrong return type, must be Task).
        /// </summary>
        internal static string FoundCommandRejectedReasonType {
            get {
                return ResourceManager.GetString("FoundCommandRejectedReasonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found possible Module container {0}..
        /// </summary>
        internal static string FoundModuleContainer {
            get {
                return ResourceManager.GetString("FoundModuleContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had to load guild data from API.(no cache).
        /// </summary>
        internal static string HadToLoadGuild {
            get {
                return ResourceManager.GetString("HadToLoadGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler is using shard ({0}) and its running status is ({1})..
        /// </summary>
        internal static string HandlerStatus {
            get {
                return ResourceManager.GetString("HandlerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord connection Initialized in {0}s..
        /// </summary>
        internal static string InitialConnectionTime {
            get {
                return ResourceManager.GetString("InitialConnectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing discord connection....
        /// </summary>
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Modules loaded in {0}s..
        /// </summary>
        internal static string LoadedCoreModules {
            get {
                return ResourceManager.GetString("LoadedCoreModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module container {0} contained {1} module(s) with {2} command(s)..
        /// </summary>
        internal static string LoadedModuleContainer {
            get {
                return ResourceManager.GetString("LoadedModuleContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules loaded in {0}s..
        /// </summary>
        internal static string LoadedModules {
            get {
                return ResourceManager.GetString("LoadedModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading CoreModules....
        /// </summary>
        internal static string LoadingCoreModules {
            get {
                return ResourceManager.GetString("LoadingCoreModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0} Module....
        /// </summary>
        internal static string LoadingModule {
            get {
                return ResourceManager.GetString("LoadingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Modules....
        /// </summary>
        internal static string LoadingModules {
            get {
                return ResourceManager.GetString("LoadingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback to Console logging..
        /// </summary>
        internal static string LoggerFallback {
            get {
                return ResourceManager.GetString("LoggerFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Commands found.({0)})..
        /// </summary>
        internal static string MultipleCommandsFound {
            get {
                return ResourceManager.GetString("MultipleCommandsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameters.
        /// </summary>
        internal static string NoParams {
            get {
                return ResourceManager.GetString("NoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} took {1}s..
        /// </summary>
        internal static string RanCommand {
            get {
                return ResourceManager.GetString("RanCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading log settings..
        /// </summary>
        internal static string ReadLogSettings {
            get {
                return ResourceManager.GetString("ReadLogSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttin down....
        /// </summary>
        internal static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup complete..
        /// </summary>
        internal static string StartupComplete {
            get {
                return ResourceManager.GetString("StartupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown complete..
        /// </summary>
        internal static string SutdownComplete {
            get {
                return ResourceManager.GetString("SutdownComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate parameter {0} with type ({1})..
        /// </summary>
        internal static string UsingDuplicateParam {
            get {
                return ResourceManager.GetString("UsingDuplicateParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using parameter {0} with type ({1}) but flagged not using..
        /// </summary>
        internal static string UsingUnflaggedParam {
            get {
                return ResourceManager.GetString("UsingUnflaggedParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter {0} with type ({1})..
        /// </summary>
        internal static string UsingUnknownParam {
            get {
                return ResourceManager.GetString("UsingUnknownParam", resourceCulture);
            }
        }
    }
}
